title: "مفكرتي الرقمية"
email: "abdullah.lajam@gmail.com"
description: "مساحتي الشخصية لمشاركة أفكاري وتجربتي في التقنية وريادة الأعمال والذكاء الاصطناعي."
baseurl: "/my-digital-notebook"
url: "https://abdullah-lajam.github.io"
theme_color: "#ffffff"
brand_color: "#0077cc"
content_width: "900px"

header_pages:
  - index.md
  - categories.md
  - about.md

markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
