# معلومات الموقع الأساسية
title: مفكرتي الرقمية
description: مساحتي الشخصية لمشاركة الأفكار والمعرفة في مجالات التقنية وريادة الأعمال
baseurl: "/my-digital-notebook"
url: "https://abdullah-lajam.github.io"
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.png"

# معلومات المؤلف
author:
  name: عبدالله سالم
  bio: خبير تقني وريادي أعمال مهتم بمشاركة المعرفة والأفكار
  email: your-email@example.com
  twitter: username
  github: abdullah-lajam
  linkedin: username
  image: "/assets/images/author.jpg"

# إعدادات التخطيط والعرض
rtl: true
permalink: /:categories/:title/
paginate: 9
paginate_path: "/page/:num/"

# الإعدادات التقنية
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# التصنيفات الرئيسية للمدونة
collections:
  categories:
    output: true
    permalink: /categories/:name/

# الملفات التي يجب استثناؤها من التوليد
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# المكونات الإضافية
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# إعدادات التحليلات (إذا كنت ترغب في تفعيلها)
google_analytics: # ضع هنا معرف Google Analytics الخاص بك

# خيارات إضافية
show_excerpts: true
excerpt_separator: <!--more-->
timezone: Asia/Riyadh
