title: "مفكّرتي الرقمية"
description: "مدونة تقنية متخصصة في الذكاء الاصطناعي – دروس، أدوات، وأفكار."
email: "you@example.com"

url: "https://abdullah-lajam.github.io"
baseurl: "/my-digital-notebook"   # غيّر إذا تغيّر اسم الريبو

permalink: /:categories/:title/
lang: ar
timezone: Asia/Riyadh

# الصفحات الظاهرة في الترويسة
header_pages:
  - index.md
  - about.md
  - categories.html

collections:
  tutorials:
    output: true
    permalink: /tutorials/:title/

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6
paginate_path: "/page/:num/"
