title: "مفكرتي الرقمية"
email: ""
author: "عبد الله"

remote_theme: MohamedAliRashad/The-Simple-Arabic-Theme

copyright: "© {currentYear} {author} - جميع الحقوق متاحة لمن يريد نفع الآخرين."

description: >-
  مساحتي الخاصة لتدوين الأفكار والمشاريع التقنية.

baseurl: "/my-digital-notebook"
url: "https://abdullah-lajam.github.io"
favicon: "/my-digital-notebook/assets/images/moon.svg"

yat:
  date_format: "%-d %b %Y"

content_width: "1080px"
editor_cache: true
like_btn: true
locale: "ar_SA"
split_editor: true

banner: null

header_pages:
  - index.html
  - ai.html
  - education.html
  - business.html
  - humanities.html
  - misc.html
  - archives.html
  - categories.html
  - about.html


markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
